# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-01 00:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=1023)),
                ('h1', models.CharField(max_length=255)),
                ('img', models.ImageField(blank=True, upload_to='')),
                ('short', models.TextField(blank=True)),
                ('author', models.CharField(default='Admin', max_length=255)),
                ('date', models.DateField(blank=True, default='2017-10-01')),
                ('post', models.TextField(blank=True)),
                ('url', models.URLField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('description', models.CharField(blank=True, max_length=1023)),
                ('h1', models.CharField(blank=True, max_length=255)),
                ('short', models.TextField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ManyToManyField(to='blog.Category'),
        ),
    ]
