# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-02 16:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20171001_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date',
            field=models.DateField(blank=True, default='2017-10-02'),
        ),
        migrations.AlterField(
            model_name='image',
            name='alt',
            field=models.CharField(max_length=255),
        ),
    ]
