# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-04 20:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20171004_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.CharField(default='Admin', max_length=255),
        ),
    ]
