# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-05 11:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20171004_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date',
            field=models.DateField(blank=True, default='2017-10-05'),
        ),
    ]
