# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-05 12:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20171005_1137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='img',
        ),
        migrations.AddField(
            model_name='article',
            name='img',
            field=models.ImageField(default='no-image.jpg', upload_to='images'),
        ),
    ]
