# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-14 22:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20171005_1215'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.AlterField(
            model_name='article',
            name='date',
            field=models.DateField(blank=True, default='2017-10-14'),
        ),
    ]
