# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-01 22:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20171001_0957'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='url',
        ),
        migrations.AlterField(
            model_name='article',
            name='description',
            field=models.CharField(blank=True, max_length=1023),
        ),
        migrations.AlterField(
            model_name='article',
            name='post',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='article',
            name='short',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
