# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-04 23:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20171204_2256'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='automatic',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='article',
            name='source',
            field=models.URLField(blank=True, max_length=1024),
        ),
    ]
